# Generated by Django 4.2.6 on 2024-02-10 07:20

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('form_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('response_user_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Formtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_name', models.CharField(max_length=100)),
                ('User_id', models.IntegerField()),
                ('Form_Url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('answer', jsonfield.fields.JSONField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('option1', models.CharField(blank=True, max_length=100)),
                ('option2', models.CharField(blank=True, max_length=100)),
                ('option3', models.CharField(blank=True, max_length=100)),
                ('option4', models.CharField(blank=True, max_length=100)),
                ('Form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_Quiz_App.formtitle')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Main_Quiz_App.formresponse')),
            ],
        ),
        migrations.AddField(
            model_name='formresponse',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_Quiz_App.formtitle'),
        ),
    ]
