# Generated by Django 4.2.6 on 2024-02-10 04:21

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Quiz_App', '0002_remove_questions_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtitle',
            name='Form_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=jsonfield.fields.JSONField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=10000),
        ),
    ]
